server:
  port: 7171
  
spring:
  application:
    name: PRODUCT-SERVICE 
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: pgAdmin
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
    show-sql: true
  sql:
    init:
      mode: ALWAYS
  

cwm:
  openapi:
    dev-url: http://localhost:7171

app:   
  secret: mayurb

