server:
  port: 7171
  
spring:
  application:
    name: PRODUCT-SERVICE  

spring.jpa:
  database: POSTGRESQL
  hibernate.ddl-auto: create-drop
  show-sql: true

spring.datasource:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/postgres
  username: postgres
  password: pgAdmin
 
 
#bezkoder.openapi.dev-url=http://localhost:8080
#bezkoder.openapi.prod-url=https://bezkoder-api.com 

cwm:
  openapi:
     dev-url: http://localhost:7171