server:
  port: 7171
  
spring:
  application:
    name: PRODUCT-SERVICE  
<<<<<<< HEAD

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: pgAdmin

  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
=======
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: pgAdmin 
  sql:
    init:
      mode: always
spring.jpa:
  database: POSTGRESQL
  hibernate.ddl-auto: create-drop
  show-sql: true

>>>>>>> 3ce653e933dbd7801270017fdf5b72a2da2d5466

cwm:
  openapi:
    dev-url: http://localhost:7171

app:   
  secret: mayurb

logging:
  level:
<<<<<<< HEAD
    org.springframework.web: DEBUG  
    org.hibernate: DEBUG
=======
    '[org.springframework.web, org.hibernate]': DEBUG  
     
>>>>>>> 3ce653e933dbd7801270017fdf5b72a2da2d5466
